
project_id = "egeufofnkpvwbmffgoxw"

[api]
enabled = true
port = 54321

[db]
port = 54322

[functions]
port = 54323

[inbucket]
port = 54324

[studio]
port = 54325

[storage]
port = 54326

[auth]
enable_strong_password = false
enable_mfa = true
mfa_remember_days = 14
mfa_methods = ["totp", "email"]
sms_autoconfirm = true
site_url = "https://egeufofnkpvwbmffgoxw.lovable.app"
additional_redirect_urls = [
  "https://egeufofnkpvwbmffgoxw.lovable.app", 
  "http://localhost:5173", 
  "http://localhost:8080"
]
disable_signup = false
cookie_secure = true

[functions.create-admin]
verify_jwt = false

[secrets]
RESEND_API_KEY = "re_Qse6YSbn_7staK5yu7e8E17t6eRgw73tp"
